### ISSUE TITLE
invalid property id (int_adyen_overlay/cartridge/scripts/adyenLevelTwoThreeData.js#70)

### ISSUE THREAD

**Issue by BerkanCetinkayaOSF** [Adyen/adyen-salesforce-commerce-cloud#452]
**Describe the bug**

Hello, we're using the current master branch and we have an error during placing an order

**To Reproduce**
1. Try to place an order with Adyen
2. See the error in the BM
int_adyen_overlay
Caused by: com.demandware.core.script.capi.ScriptingException: invalid property id (int_adyen_overlay/cartridge/scripts/adyenLevelTwoThreeData.js#70)

Order is not placed

**Expected behavior**
Order is placed

**Screenshots**
![Screen Shot 2021-04-28 at 11 54 46](https://user-images.githubusercontent.com/49192724/116376348-d6b80e00-a818-11eb-9357-1af08443d20c.png)

**Desktop (please complete the following information):**
 - All platforms

**Comment by maassenbas** [comment]
Hi @BerkanCetinkayaOSF ,
Thanks for reaching out. 
Is this happening for all products or for a specific one? 
Could you specify for what kind of product this failed (i.e. bundle product or normal product)? 
Any indication in the logs why the `id` is not known? 

Thanks,
Bas Maassen
Adyen

**Comment by BerkanCetinkayaOSF** [comment]
Hello @maassenbas,
1 - Is this happening for all products or for a specific one?
Could you specify for what kind of product this failed (i.e. bundle product or normal product)?
**It is occurring for every product.**
2 - Any indication in the logs why the id is not known?

This is the whole error log:

```
ERROR PipelineCallServlet|1629788108|Sites-Clos19_FR-Site|CheckoutServices-PlaceOrder|PipelineCall|yg4-jqJgad system.core Sites-Clos19_FR-Site STOREFRONT yg4-jqJgad 4kWsbwBiimCgAAAK-0-00 2819199709738720256 - Exception occurred during request processing: ScriptingException invalid property id (int_adyen_overlay/cartridge/scripts/adyenLevelTwoThreeData.js#70)
System
RequestID: 4kWsbwBiimCgAAAK-0-00
SessionType: STOREFRONT
Truncated SessionID: yg4-jqJgad
Customer UUID: bdDccGShpVwrY7bDdnNIAbaDfw
ServerName: 10.0.27.210
ServerPort: 10272
Request
URI: /servlet/Beehive/Sites-Clos19_FR-Site/fr_FR/CheckoutServices-PlaceOrder
Method: POST
PathInfo: /Sites-Clos19_FR-Site/fr_FR/CheckoutServices-PlaceOrder
Remote Address: 171.79.75.155
Parameters
Stack trace <0230581802e71dcd4a470b3a65c44616>
com.demandware.core.script.capi.ScriptingException: invalid property id (int_adyen_overlay/cartridge/scripts/adyenLevelTwoThreeData.js#70)
	at int_adyen_overlay/cartridge/scripts/adyenCheckout.js:53
	at int_adyen_SFRA/cartridge/scripts/hooks/payment/processor/adyen_component.js:75 (Authorize)
	at int_adyen_SFRA/cartridge/scripts/checkout/adyenHelpers.js:45 (handlePayments)
	at int_adyen_SFRA/cartridge/controllers/CheckoutServices.js:159 (anonymous)
	at modules/server/route.js:85 (next)
	at modules/server/middleware.js:42 (https)
	at modules/server/route.js:93 (anonymous)
Caused by: com.demandware.core.script.capi.ScriptingException: invalid property id (int_adyen_overlay/cartridge/scripts/adyenLevelTwoThreeData.js#70)
	at com.demandware.core.script2.capi.RhinoEvalScope.createScriptingException(RhinoEvalScope.java:616)
	at com.demandware.core.script2.internal.scriptobject.JSFunctionImpl.call(JSFunctionImpl.java:79)
	at com.demandware.beehive.core.internal.controller.ControllerMgrImpl.invokeController(ControllerMgrImpl.java:311)
	at com.demandware.beehive.core.internal.controller.ControllerMgrImpl.invokeController(ControllerMgrImpl.java:241)
	at com.demandware.beehive.core.internal.controller.ControllerMgrImpl.invokeController(ControllerMgrImpl.java:164)
	at com.demandware.beehive.core.internal.request.PipelineCallServlet.serviceInternal(PipelineCallServlet.java:399)
	at com.demandware.beehive.core.internal.request.PipelineCallServlet.service(PipelineCallServlet.java:197)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.AnalyticsHandlerFilter.doFilter(AnalyticsHandlerFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.TrackingConsentCookieFilter.doFilter(TrackingConsentCookieFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.EffectiveContextFilter.doFilter(EffectiveContextFilter.java:142)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.PreparePipelineCallFilter.doFilter(PreparePipelineCallFilter.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.pagemarker.PageMarkerFilter.doFilter(PageMarkerFilter.java:95)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.EcomRequestFilter.doFilter(EcomRequestFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.seo.SEOServletFilter.doFilter(SEOServletFilter.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.url.URLServletFilter.doFilter(URLServletFilter.java:179)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.DetectCharsetFilter.doFilter(DetectCharsetFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.AnalyticsTrackingFilter.doFilter(AnalyticsTrackingFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.UserAgentMetricTrackingFilter.doFilter(UserAgentMetricTrackingFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.MetricTrackingFilter.doFilter(MetricTrackingFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.PCIComplianceFilter.doFilter(PCIComplianceFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.ActivityFilter.doFilter(ActivityFilter.java:323)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:381)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: script2.org.mozilla.javascript.EvaluatorException: invalid property id (int_adyen_overlay/cartridge/scripts/adyenLevelTwoThreeData.js#70)
	at script2.org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
	at script2.org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
	at com.demandware.core.script2.internal.engine.ScriptContextFactory$WarnLoggingErrorReporter.error(ScriptContextFactory.java:411)
	at script2.org.mozilla.javascript.Parser.addError(Parser.java:259)
	at script2.org.mozilla.javascript.Parser.reportError(Parser.java:327)
	at script2.org.mozilla.javascript.Parser.reportError(Parser.java:314)
	at script2.org.mozilla.javascript.Parser.reportError(Parser.java:307)
	at script2.org.mozilla.javascript.Parser.objectLiteral(Parser.java:3622)
	at script2.org.mozilla.javascript.Parser.primaryExpr(Parser.java:3178)
	at script2.org.mozilla.javascript.Parser.memberExpr(Parser.java:2802)
	at script2.org.mozilla.javascript.Parser.unaryExpr(Parser.java:2680)
	at script2.org.mozilla.javascript.Parser.mulExpr(Parser.java:2601)
	at script2.org.mozilla.javascript.Parser.addExpr(Parser.java:2585)
	at script2.org.mozilla.javascript.Parser.shiftExpr(Parser.java:2566)
	at script2.org.mozilla.javascript.Parser.relExpr(Parser.java:2541)
	at script2.org.mozilla.javascript.Parser.eqExpr(Parser.java:2513)
	at script2.org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2502)
	at script2.org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2491)
	at script2.org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2480)
	at script2.org.mozilla.javascript.Parser.andExpr(Parser.java:2469)
	at script2.org.mozilla.javascript.Parser.orExpr(Parser.java:2458)
	at script2.org.mozilla.javascript.Parser.condExpr(Parser.java:2422)
	at script2.org.mozilla.javascript.Parser.assignExpr(Parser.java:2378)
	at script2.org.mozilla.javascript.Parser.argumentList(Parser.java:2753)
	at script2.org.mozilla.javascript.Parser.memberExprTail(Parser.java:2919)
	at script2.org.mozilla.javascript.Parser.memberExpr(Parser.java:2838)
	at script2.org.mozilla.javascript.Parser.unaryExpr(Parser.java:2680)
	at script2.org.mozilla.javascript.Parser.mulExpr(Parser.java:2601)
	at script2.org.mozilla.javascript.Parser.addExpr(Parser.java:2585)
	at script2.org.mozilla.javascript.Parser.shiftExpr(Parser.java:2566)
	at script2.org.mozilla.javascript.Parser.relExpr(Parser.java:2541)
	at script2.org.mozilla.javascript.Parser.eqExpr(Parser.java:2513)
	at script2.org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2502)
	at script2.org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2491)
	at script2.org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2480)
	at script2.org.mozilla.javascript.Parser.andExpr(Parser.java:2469)
	at script2.org.mozilla.javascript.Parser.orExpr(Parser.java:2458)
	at script2.org.mozilla.javascript.Parser.condExpr(Parser.java:2422)
	at script2.org.mozilla.javascript.Parser.assignExpr(Parser.java:2378)
	at script2.org.mozilla.javascript.Parser.argumentList(Parser.java:2753)
	at script2.org.mozilla.javascript.Parser.memberExprTail(Parser.java:2919)
	at script2.org.mozilla.javascript.Parser.memberExpr(Parser.java:2838)
	at script2.org.mozilla.javascript.Parser.unaryExpr(Parser.java:2680)
	at script2.org.mozilla.javascript.Parser.mulExpr(Parser.java:2601)
	at script2.org.mozilla.javascript.Parser.addExpr(Parser.java:2585)
	at script2.org.mozilla.javascript.Parser.shiftExpr(Parser.java:2566)
	at script2.org.mozilla.javascript.Parser.relExpr(Parser.java:2541)
	at script2.org.mozilla.javascript.Parser.eqExpr(Parser.java:2513)
```

**Comment by maassenbas** [comment]
Hi @BerkanCetinkayaOSF ,

Thanks for your follow up. 
This was a known issue and is related to the Babel transpile configuration.
Could you please do following steps as described in [this comment](https://github.com/Adyen/adyen-salesforce-commerce-cloud/issues/406#issuecomment-752403090)?
This will fix your issue.

Kind regards,
Bas Maassen
Adyen
